twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': mon_app
    file_name_pattern: '*.twig'
    # form_themes: ['bootstrap_5_layout.html.twig']
    form_themes:
        - '@mon_app/form/bootstrap-layout.html.twig'


when@test:
    twig:
        strict_variables: true
